// File generated by the FlutterFire CLI for project `rideclub`.
//
// android + ios values below are REAL. `databaseURL` was added by hand because
// the Realtime Database (needed from Phase 3: live location, chat, presence)
// must be created in the console first; the CLI omits the URL until then.
//
// ⚠️ If you created the RTDB in a non-US region, update `databaseURL` to match
//    the URL shown in Firebase Console → Realtime Database (e.g.
//    https://<project>-default-rtdb.asia-southeast1.firebasedatabase.app).
//
// Re-running `flutterfire configure --platforms=android,ios` refreshes the
// android/ios blocks; re-add `databaseURL` afterward if the CLI drops it.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] per platform. Consumed by `Firebase.initializeApp`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios; // reuse iOS config for macOS if you enable it
      default:
        // RideClub is a mobile app (Phone OTP, GPS, background location).
        // If you see this, you launched on Windows/web/linux — run it on an
        // Android or iOS device/emulator instead, e.g.:
        //     flutter run -d emulator-5554
        throw UnsupportedError(
          'RideClub runs on Android and iOS only. '
          'Current platform: $defaultTargetPlatform. '
          'Launch on an Android/iOS device or emulator (e.g. '
          '`flutter run -d <android-device-id>`).',
        );
    }
  }

  // databaseURL is REQUIRED for Realtime Database (Phases 3/5/6). Create the
  // RTDB in the console, then confirm this matches the URL it shows. Default
  // (US) form below; for Asia/EU use e.g.
  // https://ridetogether-nwaytech-default-rtdb.asia-southeast1.firebasedatabase.app
  static const String _databaseUrl =
      'https://ridetogether-nwaytech-default-rtdb.firebaseio.com';

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfxkMNLUOPp1Zr5dnp9Z56UN6pB7LK1lg',
    appId: '1:613319021790:android:76f202c566ee4292eade4f',
    messagingSenderId: '613319021790',
    projectId: 'ridetogether-nwaytech',
    storageBucket: 'ridetogether-nwaytech.firebasestorage.app',
    databaseURL: _databaseUrl,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz2Th3zCBnBgkpFcvSRRFiArcwt580dlw',
    appId: '1:613319021790:ios:c07753edb4c88d71eade4f',
    messagingSenderId: '613319021790',
    projectId: 'ridetogether-nwaytech',
    storageBucket: 'ridetogether-nwaytech.firebasestorage.app',
    iosBundleId: 'com.ridetogether.app',
    databaseURL: _databaseUrl,
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WEB_API_KEY',
    appId: 'REPLACE_WEB_APP_ID',
    messagingSenderId: 'REPLACE_SENDER_ID',
    projectId: 'REPLACE_PROJECT_ID',
    storageBucket: 'REPLACE_PROJECT_ID.appspot.com',
    databaseURL: 'https://REPLACE_PROJECT_ID-default-rtdb.firebaseio.com',
    authDomain: 'REPLACE_PROJECT_ID.firebaseapp.com',
  );
}
