// vexp-guard - opencode plugin (generated by 'vexp setup-agents').
// Forces the agent onto vexp's run_pipeline by blocking opencode's native
// grep/glob (and shelled-out tree search) WHILE the vexp daemon is healthy.
// Fails OPEN when the daemon is down, so native search still works with no index.
// Mirrors vexp's Claude Code PreToolUse guard (.claude/hooks/vexp-guard.sh).
import { existsSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";

// Walk up from start to the first ancestor that owns a .vexp dir.
function findVexpDir(start) {
  let dir = start;
  for (;;) {
    if (existsSync(join(dir, ".vexp"))) return join(dir, ".vexp");
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

// Is the pid in .vexp/daemon.pid a live process? Guards stale files left after
// a kill -9: healthy + socket can linger, so existence alone is not enough.
function pidAlive(pidFile) {
  let pid = 0;
  try { pid = parseInt(readFileSync(pidFile, "utf-8").trim(), 10); } catch (e) { return false; }
  if (!pid) return false;
  try { process.kill(pid, 0); return true; } catch (e) { return !!(e && e.code === "EPERM"); }
}

// The daemon writes .vexp/healthy when up and removes it on graceful shutdown.
// Unix: also require a live socket AND a live pid. Windows has no socket file,
// so the daemon drops a .vexp/daemon.pipe marker instead. A dead daemon fails
// open so native search still works.
function daemonHealthy(vexpDir) {
  if (!vexpDir || !existsSync(join(vexpDir, "healthy"))) return false;
  if (process.platform === "win32") return existsSync(join(vexpDir, "daemon.pipe"));
  return existsSync(join(vexpDir, "daemon.sock")) && pidAlive(join(vexpDir, "daemon.pid"));
}

const SEARCH_TOOLS = new Set(["grep", "glob"]);
const SHELL_SEARCH_BINS = ["rg", "grep", "egrep", "fgrep", "ag", "ack", "find", "fd", "fdfind"];

// True when a bash command's first token is a tree-search binary (grep/rg/find).
function isShellSearch(command) {
  const t = (command || "").trim();
  for (const b of SHELL_SEARCH_BINS) {
    if (t === b || t.indexOf(b + " ") === 0) return true;
  }
  return false;
}

export const VexpGuard = async ({ directory, worktree }) => {
  const root = worktree || directory || ".";
  let vexpDir = null;
  return {
    "tool.execute.before": async (input, output) => {
      if (!vexpDir) vexpDir = findVexpDir(root);
      if (!daemonHealthy(vexpDir)) return;
      if (SEARCH_TOOLS.has(input.tool)) {
        throw new Error(
          "vexp daemon is running - call run_pipeline instead of " + input.tool +
          " (pre-indexed, graph-ranked, ~60% fewer tokens)."
        );
      }
      if (input.tool === "bash" && isShellSearch(output && output.args && output.args.command)) {
        throw new Error(
          "vexp daemon is running - call run_pipeline instead of shell search (grep/rg/find)."
        );
      }
    },
  };
};
